/*
 * AbstractConfigurationDialog.java
 *
 * Created on 06-Jun-2005
 */

package suncertify.presentation;

import java.util.ResourceBundle;
import javax.swing.JDialog;
import javax.swing.JPanel;

/**
 * 
 * @author Richard Wardle
 */
public abstract class AbstractConfigurationDialog extends JDialog 
        implements ConfigurationView {

    private final ResourceBundle bundle;
    private ConfigurationPresenter presenter;

    protected AbstractConfigurationDialog() {
        // TODO Get resource bundle from app context?
        this.bundle = ResourceBundle.getBundle("suncertify/presentation/Bundle");
        this.setModal(true);
        initComponents();
    }

    protected final ResourceBundle getResourceBundle() {
        return this.bundle;
    }

    public final void setPresenter(ConfigurationPresenter presenter) {
        this.presenter = presenter;
    }

    /**
     * Gets the text to display in the message area.
     * 
     * @return The message text.
     */
    protected abstract String getMessageText();

    /**
     * Initialises the input panel. 
     * <p/> 
     * This method is called from the <code>initComponents</code> method.
     * @param inputPanel the input panel.
     */
    protected abstract void initInputPanel(JPanel inputPanel);

    /**
     * {@inheritDoc}
     */
    public final void realise() {
        this.pack();
        this.setVisible(true);
    }

    /**
     * {@inheritDoc}
     */
    public final void close() {
        this.setVisible(false);
        this.dispose();
    }

    /**
     * Gets the state of the OK button.
     * 
     * @return <code>true</code> if it is enabled, <code>false</code> if it
     *         is disabled.
     */
    protected final boolean isOkButtonEnabled() {
        return this.okButton.isEnabled();
    }

    /**
     * Sets the state of the OK button.
     * 
     * @param enabled
     *            <code>true</code> if it should be enabled,
     *            <code>false</code> if it should be disabled.
     */
    protected final void setOkButtonEnabled(boolean enabled) {
        this.okButton.setEnabled(enabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">
    private void initComponents() {

        inputPanel = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        messageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        initInputPanel(inputPanel);

        java.util.ResourceBundle bundle = java.util.ResourceBundle
                .getBundle("suncertify/presentation/Bundle"); // NOI18N
        okButton.setText(bundle.getString("AbstractConfigurationDialog.okButton.text")); // NOI18N
        okButton.setName("AbstractConfigurationDialog.okButton.name"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText(bundle.getString("AbstractConfigurationDialog.cancelButton.text")); // NOI18N
        cancelButton.setName("AbstractConfigurationDialog.cancelButton.text"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout buttonPanelLayout = new org.jdesktop.layout.GroupLayout(
                buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(buttonPanelLayout.createParallelGroup(
                org.jdesktop.layout.GroupLayout.LEADING).add(
                buttonPanelLayout.createSequentialGroup().add(okButton).addPreferredGap(
                        org.jdesktop.layout.LayoutStyle.RELATED).add(cancelButton).addContainerGap(
                        34, Short.MAX_VALUE)));
        buttonPanelLayout.setVerticalGroup(buttonPanelLayout.createParallelGroup(
                org.jdesktop.layout.GroupLayout.LEADING).add(
                buttonPanelLayout.createSequentialGroup().add(
                        buttonPanelLayout.createParallelGroup(
                                org.jdesktop.layout.GroupLayout.BASELINE).add(okButton).add(
                                cancelButton)).addContainerGap(
                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        messageLabel.setText(getMessageText());
        messageLabel.setName("AbstractConfigurationDialog.messageLabel.name"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
                getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(
                org.jdesktop.layout.GroupLayout.LEADING).add(
                layout.createSequentialGroup().add(
                        layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                                layout.createSequentialGroup().addContainerGap().add(inputPanel,
                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)).add(
                                layout.createSequentialGroup().addContainerGap().add(buttonPanel,
                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)).add(
                                layout.createSequentialGroup().add(23, 23, 23).add(messageLabel)))
                        .addContainerGap(96, Short.MAX_VALUE)));
        layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(
                        layout.createSequentialGroup().add(20, 20, 20).add(messageLabel)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(
                                        inputPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(8, 8, 8).add(buttonPanel,
                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)));

        pack();
    }// </editor-fold>

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {
        this.presenter.cancelButtonActionPerformed();
    }

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {
        this.presenter.okButtonActionPerformed();
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JButton okButton;
    // End of variables declaration
}
