/*
 * AbstractConfigurationDialog.java
 *
 * 10 Aug 2007
 */

package suncertify.presentation;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ResourceBundle;

import javax.swing.JDialog;
import javax.swing.JPanel;

/**
 * 
 * @author Richard Wardle
 */
public abstract class AbstractConfigurationDialog extends JDialog implements
        ConfigurationView {

    private final ResourceBundle resourceBundle;
    private ConfigurationPresenter presenter;

    /** Constructor. */
    protected AbstractConfigurationDialog() {
        // TODO Dialog has no taskbar entry on Windows because it has no parent,
        // consider making this a JFrame so it does have one?

        // TODO Change generated code to use this bundle
        this.resourceBundle = ResourceBundle
                .getBundle("suncertify/presentation/Bundle");
        setModal(true);
        initComponents();
    }

    /**
     * Gets the resource bundle.
     * 
     * @return The resource bundle.
     */
    protected final ResourceBundle getResourceBundle() {
        return this.resourceBundle;
    }

    /** {@inheritDoc} */
    public final void setPresenter(ConfigurationPresenter presenter) {
        this.presenter = presenter;
    }

    /** {@inheritDoc} */
    public final void realise() {
        pack();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension dialogSize = getSize();
        setLocation((screenSize.width - dialogSize.width) / 2,
                (screenSize.height - dialogSize.height) / 2);
        setVisible(true);
    }

    /** {@inheritDoc} */
    public final void close() {
        setVisible(false);
        dispose();
    }

    /**
     * Gets the state of the OK button.
     * 
     * @return <code>true</code> if the button is enabled, <code>false</code>
     *         if the button is disabled.
     */
    protected final boolean isOkButtonEnabled() {
        return this.okButton.isEnabled();
    }

    /**
     * Sets the state of the OK button.
     * 
     * @param enabled
     *                <code>true</code> if it should be enabled,
     *                <code>false</code> if it should be disabled.
     */
    protected final void setOkButtonEnabled(boolean enabled) {
        this.okButton.setEnabled(enabled);
    }

    /**
     * Initialises the input panel. <p/> This method is called from the
     * <code>initComponents</code> method.
     * 
     * @param inputPanel
     *                The input panel.
     */
    protected abstract void initInputPanel(JPanel inputPanel);

    /**
     * Gets the text to display in the message area.
     * 
     * @return The message text.
     */
    protected abstract String getMessageText();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code
    // ">//GEN-BEGIN:initComponents
    private void initComponents() {

        this.inputPanel = new javax.swing.JPanel();
        this.buttonPanel = new javax.swing.JPanel();
        this.okButton = new javax.swing.JButton();
        this.cancelButton = new javax.swing.JButton();
        this.messageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle
                .getBundle("suncertify/presentation/Bundle"); // NOI18N
        setTitle(bundle.getString("AbstractConfigurationDialog.title")); // NOI18N

        initInputPanel(this.inputPanel);

        this.okButton.setText(bundle
                .getString("AbstractConfigurationDialog.okButton.text")); // NOI18N
        this.okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        this.cancelButton.setText(bundle
                .getString("AbstractConfigurationDialog.cancelButton.text")); // NOI18N
        this.cancelButton
                .addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        cancelButtonActionPerformed(evt);
                    }
                });

        org.jdesktop.layout.GroupLayout buttonPanelLayout = new org.jdesktop.layout.GroupLayout(
                this.buttonPanel);
        this.buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout
                .setHorizontalGroup(buttonPanelLayout
                        .createParallelGroup(
                                org.jdesktop.layout.GroupLayout.LEADING)
                        .add(
                                buttonPanelLayout
                                        .createSequentialGroup()
                                        .addContainerGap()
                                        .add(this.okButton)
                                        .addPreferredGap(
                                                org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(this.cancelButton)
                                        .addContainerGap(31, Short.MAX_VALUE)));
        buttonPanelLayout
                .setVerticalGroup(buttonPanelLayout
                        .createParallelGroup(
                                org.jdesktop.layout.GroupLayout.LEADING)
                        .add(
                                buttonPanelLayout
                                        .createSequentialGroup()
                                        .addContainerGap()
                                        .add(
                                                buttonPanelLayout
                                                        .createParallelGroup(
                                                                org.jdesktop.layout.GroupLayout.BASELINE)
                                                        .add(this.okButton)
                                                        .add(this.cancelButton))
                                        .addContainerGap(
                                                org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)));

        this.messageLabel.setText(getMessageText());

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
                getContentPane());
        getContentPane().setLayout(layout);
        layout
                .setHorizontalGroup(layout
                        .createParallelGroup(
                                org.jdesktop.layout.GroupLayout.LEADING)
                        .add(
                                layout
                                        .createSequentialGroup()
                                        .addContainerGap()
                                        .add(
                                                layout
                                                        .createParallelGroup(
                                                                org.jdesktop.layout.GroupLayout.LEADING)
                                                        .add(
                                                                this.inputPanel,
                                                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                                                org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                        .add(
                                                                this.buttonPanel,
                                                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                                                org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                        .add(this.messageLabel))
                                        .addContainerGap(16, Short.MAX_VALUE)));
        layout.setVerticalGroup(layout.createParallelGroup(
                org.jdesktop.layout.GroupLayout.LEADING).add(
                layout.createSequentialGroup().addContainerGap().add(
                        this.messageLabel).add(44, 44, 44).add(this.inputPanel,
                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(
                                org.jdesktop.layout.LayoutStyle.RELATED,
                                org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE).add(this.buttonPanel,
                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(20, 20, 20)));
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {
        this.presenter.cancelButtonActionPerformed();
    }

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {
        this.presenter.okButtonActionPerformed();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

}
