/*
 * MainFrame.java
 *
 * 06 Jun 2007
 */

package suncertify.presentation;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ResourceBundle;

import javax.swing.JFrame;

/**
 * 
 * @author Richard Wardle
 */
public final class MainFrame extends JFrame implements MainView {

    private static final long serialVersionUID = 1L;
    private final ResourceBundle resourceBundle;
    private MainPresenter presenter;

    public MainFrame() {
        // TODO Change generated code to use this bundle
        this.resourceBundle = ResourceBundle
                .getBundle("suncertify/presentation/Bundle");
        initComponents();
    }

    public void setPresenter(MainPresenter presenter) {
        this.presenter = presenter;
    }

    public void realise() {
        pack();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension dialogSize = getSize();
        setLocation((screenSize.width - dialogSize.width) / 2,
                (screenSize.height - dialogSize.height) / 2);
        setVisible(true);
    }

    public void setLabelText(String text) {
        this.label.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code
    // ">//GEN-BEGIN:initComponents
    private void initComponents() {

        this.helloButton = new javax.swing.JButton();
        this.label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        java.util.ResourceBundle bundle = java.util.ResourceBundle
                .getBundle("suncertify/presentation/Bundle"); // NOI18N
        this.helloButton
                .setText(bundle.getString("MainFrame.helloButton.text")); // NOI18N
        this.helloButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helloButtonActionPerformed(evt);
            }
        });

        this.label.setText(bundle.getString("MainFrame.label.text")); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
                getContentPane());
        getContentPane().setLayout(layout);
        layout
                .setHorizontalGroup(layout.createParallelGroup(
                        org.jdesktop.layout.GroupLayout.LEADING).add(
                        layout.createSequentialGroup().addContainerGap().add(
                                this.helloButton).addPreferredGap(
                                org.jdesktop.layout.LayoutStyle.RELATED).add(
                                this.label).addContainerGap(158,
                                Short.MAX_VALUE)));
        layout.setVerticalGroup(layout.createParallelGroup(
                org.jdesktop.layout.GroupLayout.LEADING).add(
                layout.createSequentialGroup().addContainerGap().add(
                        layout.createParallelGroup(
                                org.jdesktop.layout.GroupLayout.BASELINE).add(
                                this.helloButton).add(this.label))
                        .addContainerGap(
                                org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void helloButtonActionPerformed(java.awt.event.ActionEvent evt) {
        this.presenter.helloButtonActionPerformed();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton helloButton;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables

}
