/*
 * MainFrame.java
 *
 * Created on 06-Jun-2005
 */

package suncertify.presentation;

import javax.swing.JFrame;

/**
 *
 * @author Richard Wardle
 */
public final class MainFrame extends JFrame implements MainView {
    
    private MainPresenter presenter;
    
    public MainFrame() {
        initComponents();
    }
    
    public void setPresenter(MainPresenter presenter) {
        this.presenter = presenter;
    }
    
    public void realise() {
        this.pack();
        this.setVisible(true);
    }
    
    public void setLabelText(String text) {
        this.label.setText(text);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">                          
    private void initComponents() {

        helloButton = new javax.swing.JButton();
        label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("suncertify/presentation/Bundle"); // NOI18N
        helloButton.setText(bundle.getString("MainFrame.helloButton.text")); // NOI18N
        helloButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helloButtonActionPerformed(evt);
            }
        });

        label.setText(bundle.getString("MainFrame.label.text")); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(helloButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(label)
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(helloButton)
                    .add(label))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

private void helloButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
    this.presenter.helloButtonActionPerformed();
}                                           
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton helloButton;
    private javax.swing.JLabel label;
    // End of variables declaration                   
}
